name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Node.js-Umgebung einrichten
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Sichere, moderne Version
          cache: 'npm' # Caching für schnellere Builds

      # 3. Abhängigkeiten installieren
      - name: Install Dependencies
        run: npm ci # Sauberere Installation als `npm install`

      # 4. App bauen
      - name: Build React App
        run: npm run build

      # 5. Deployment vorbereiten
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatische Authentifizierung
          publish_dir: build # Das Output-Verzeichnis des Builds
